### ISSUE TITLE
how can I get the coordinates of the eye-track points in the world view

### ISSUE THREAD

**Issue by Y-pandaman** [pupil-labs/pupil#2178]
Hi, how can I get the coordinates of the eye-track points in the world view, I have these data now:
```
diameter: 19.2537832723
    confidence: 1.0
    model_id: 0
    model_confidence: 1.0
    pupil_timestamp: 19135.7830362
    model_birth_timestamp: 0.0
    diameter_3d: -5830174.17739
    method: ''
    topic: "pupil.1.3d"
    phi: -1.85660011517
    theta: 1.30883943009
    id: 1
    norm_pos: 
      x: 0.325790457729
      y: 0.351124236315
      z: 0.0
    projected_sphere_axes: 
      x: 3.39965073563
      y: 3.39965073563
      z: 0.0
    projected_sphere_angle: 0.0
    projected_sphere_center: 
      x: 64.1765520944
      y: 124.986970598
      z: 0.0
    sphere_radius: 10.3923048454
    sphere_center: 
      x: -71557.6212315
      y: 76767.7553603
      z: -13611822.8305
    ellipse_axes: 
      x: 17.5398531807
      y: 19.2537832723
      z: 0.0
    ellipse_angle: 48.197613583
    ellipse_center: 
      x: 62.551767884
      y: 124.584146628
      z: 0.0
    circle_3d_radius: -2915087.0887
    circle_3d_center: 
      x: -71560.4511677
      y: 76770.4466678
      z: -13611832.4611
    circle_3d_normal: 
      x: -0.272310740343
      y: 0.258971183813
      z: -0.926704260618

```

```
gazes: 
  - 
    confidence: 1.0
    norm_pos: 
      x: 0.994254022255
      y: 1.15792072264
      z: 0.0
    gaze_point_3d: 
      x: 7237892.13836
      y: -9967655.48389
      z: 4740183.02802
    gaze_normal_3d: 
      x: 0.417557034886
      y: -0.907730531952
      z: 0.0408828078602
    pupil_timestamp: 19691.2590325
    eye_center_3d: 
      x: 7237683.35984
      y: -9967201.61863
      z: 4740162.58662

```
